In [1]:
from Kmedias import *
from Bayes import *

In [2]:
df = pd.read_csv('Iris2Clases.txt', header=None)
X = np.array(df.iloc[:, :-1])
Y = np.array(df.iloc[:, -1])

V = np.array([[4.5, 3.0, 4.0, 0.0], [6.8, 3.4, 4.6, 0.7]])
vName = ['Iris-setosa', 'Iris-versicolor']

b = 2
epsilon = 0.02

In [3]:
V_KMedias = trainKMedias(X, V, b, epsilon)
testKMedias(V_KMedias, vName)


########## ENTRENAMIENTO DE K-MEDIAS ##########


En la iteración 0 los centroides son:
[[4.5 3.  4.  0. ]
 [6.8 3.4 4.6 0.7]]

En la iteración 1 los centroides son:
[[5.10395866 3.16786413 2.09623961 0.49170174]
 [5.95903834 3.00008175 3.83607486 1.15529124]]

En la iteración 2 los centroides son:
[[5.00995989 3.3798558  1.53281933 0.27036345]
 [5.96277094 2.8050755  4.26341252 1.32311517]]

Hemos terminado en la iteración 3, con los centroides:
[[5.00442052 3.40156079 1.48823286 0.25325648]
 [5.97356112 2.79282529 4.30323088 1.33817883]]

########## TEST DE K-MEDIAS ##########
El archivo TestIris01.txt pertenece al centroide situado en
[5.00442052 3.40156079 1.48823286 0.25325648] -> Iris-setosa

El archivo TestIris02.txt pertenece al centroide situado en
[5.97356112 2.79282529 4.30323088 1.33817883] -> Iris-versicolor

El archivo TestIris03.txt pertenece al centroide situado en
[5.00442052 3.40156079 1.48823286 0.25325648] -> Iris-setosa



In [4]:
medias = bayes(X, Y, vName)
testBayes(medias, vName)


########## ENTRENAMIENTO DE BAYES ##########

Las covariantes obtenidas son: 
[[[0.121764 0.098292 0.015816 0.010336]
  [0.098292 0.142276 0.011448 0.011208]
  [0.015816 0.011448 0.029504 0.005584]
  [0.010336 0.011208 0.005584 0.011264]]

 [[0.261104 0.08348  0.17924  0.054664]
  [0.08348  0.0965   0.081    0.04038 ]
  [0.17924  0.081    0.2164   0.07164 ]
  [0.054664 0.04038  0.07164  0.038324]]]

########## TEST DE BAYES ##########
El archivo TestIris01.txt pertenece a la clase 
Iris-setosa

El archivo TestIris02.txt pertenece a la clase 
Iris-versicolor

El archivo TestIris03.txt pertenece a la clase 
Iris-setosa

